#!/bin/sh
​
#Install a LAMP stack
dnf install -y httpd wget php-fpm php-mysqli php-json php php-devel
dnf install -y mariadb105-server
dnf install -y httpd php-mbstring
​
#Start the web server
chkconfig httpd on
systemctl start httpd
​
#Install the web pages for our lab
if [ ! -f /var/www/html/immersion-day-app-php7.zip ]; then
   cd /var/www/html
   wget -O 'immersion-day-app-php7.zip' 'https://static.us-east-1.prod.workshops.aws/72908d08-f6f0-4dd2-857c-d35c83790861/assets/immersion-day-app-php7.zip?Key-Pair-Id=K36Q2WVO3JP7QD&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9zdGF0aWMudXMtZWFzdC0xLnByb2Qud29ya3Nob3BzLmF3cy83MjkwOGQwOC1mNmYwLTRkZDItODU3Yy1kMzVjODM3OTA4NjEvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxOTI5MzYxN319fV19&Signature=p2GCkubtsn12KoIyqoLNoDSBs9YOZZn0FZ5WDe4y3zW69E2SmypsWl0fHMnZ-iePYhdk9kT7dCsi9kRUE25VZeAPq6GmaLu3J-GohzFxGW6lQAuGKvr2~1SDwQRRbeZfLoR7W7Z6Mej4aqR-NOstXKtHZOmzbmARiOUGwm6iMdvT3-OtXPMG4mS~~FWNOlyAc9qts5LQjtAl5uwDN3iBk2OnJ5S5D46OJSHlVEgZrp~-PCI4c-9iCboWz846xDvzAteLFU6Ftd0hi3w5RoG1l0jvAjxv9HOXidcFNCTIu90BkgX0EiVWrOAppgDgWLaL1Qdx7MGHH-~AXjb6qtv1sw__'
   unzip immersion-day-app-php7.zip
fi
​
#Install the AWS SDK for PHP
if [ ! -f /var/www/html/aws.zip ]; then
   cd /var/www/html
   mkdir vendor
   cd vendor
   wget https://docs.aws.amazon.com/aws-sdk-php/v3/download/aws.zip
   unzip aws.zip
fi
​
# Update existing packages
dnf update -y
